version: '3.8'

services:
  runner:
    build:
      context: ./docker
      dockerfile: Dockerfile
    environment:
      # Required: Set these in .env file
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_REPOSITORY=${GITHUB_REPOSITORY:-}
      - GITHUB_ORGANIZATION=${GITHUB_ORGANIZATION:-}
      
      # Optional configuration
      - RUNNER_NAME=${RUNNER_NAME:-ephemeral-runner}
      - RUNNER_GROUP=${RUNNER_GROUP:-default}
      - LABELS=${LABELS:-self-hosted,Linux,X64,ephemeral,docker}
      - EPHEMERAL=${EPHEMERAL:-true}
    volumes:
      # Mount Docker socket for Docker-outside-of-Docker
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Optional: Mount for caching (comment out for true ephemeral)
      # - ./cache:/home/runner/.cache
    restart: unless-stopped
    # For multiple runners, use scale
    # deploy:
    #   replicas: 3